# Rizwan Saddique Assignment : Numpy Function Batch No.9/2020 
PIAIC Roll Number PIAIC99311

In [3]:
import numpy as np

In [4]:
#Method 1: Return array 5 x 5 including all zeros
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
#Method 2:Return array 4 x 4 including all ones
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
#Method 3 return array 3 x3 including any random numbersMethod#3 
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.63234836e-321],
       [2.35703320e-301, 1.10618047e-046, 3.41289074e-085]])

In [10]:
#Method 4 return array number satrt from 1 to 10 with step size 2
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [16]:
x = np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
#Method 5 return shape of any array
x.shape

(5, 5)

In [18]:
#Method 6 this function change the shape of array
x.reshape(2,2,2,2)

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [19]:
#Method 7 this functon return the dimmension of array
x.ndim 

2

In [20]:
#Method 8 this function return the datatype of array
x.dtype

dtype('float64')

In [21]:
list = [2,6,7,8,9]# create simple list

In [22]:
#Method 9 this function convert the list in to array and it return 1 dimensional array
np.array(list)

array([2, 6, 7, 8, 9])

In [32]:
#Method 10 this method create random number of 1 dimensional array
first = np.random.randn(7)
second= np.random.randn(7)

In [33]:
first


array([-0.17223164,  1.36255367, -1.13276297,  0.50955258, -1.62566467,
       -0.60809169,  0.11562576])

In [34]:
second

array([ 0.2892385 ,  0.32840162, -0.72508939, -1.20224265,  0.49425587,
        1.1640641 , -0.4549865 ])

In [44]:

y = np.array([1,3,9,7,8])
k = np.array(([2,4,5,10,11]))


In [91]:
#method 11 this method return the square root of array
np.sqrt(y)

array([1.        , 1.73205081, 3.        , 2.64575131, 2.82842712])

In [92]:
#method 12 this return the power of array element
np.power(y,3)

array([  1,  27, 729, 343, 512], dtype=int32)

In [98]:
#method 13 this return the maximum value b/w two array
np.maximum(y,3)

array([3, 3, 9, 7, 8])

In [95]:
#method 14 this return the 1 on diagonals
np.eye((3)) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
#Method 15: diag: show the specify value in diagnoal
z = np.diag([4,5,7])
z

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 7]])

In [62]:
age = np.array([0,-1,12,13,14])

In [63]:
#Method 16 np.where remove missing value
np.where(age<= 0,10,age) 

array([10, 10, 12, 13, 14])

In [64]:
a = np.array([2,5,6,7,8,9])

In [65]:
#Method 17 this function return the mean value 
a.mean()

6.166666666666667

In [66]:
#Method 18 this function retyrn the sum 
a.sum()

37

In [67]:
#Method 19 adding number of series
a.cumsum()

array([ 2,  7, 13, 20, 28, 37], dtype=int32)

In [68]:
#Method 20  mutiplication number of series
a.cumprod()

array([    2,    10,    60,   420,  3360, 30240], dtype=int32)

In [74]:
b = np.array([10,5,7,10,7])

In [75]:
b>5

array([ True, False,  True,  True,  True])

In [76]:
#Method 21 #check weather one or more value in an array is true
b.any() 

True

In [78]:
#Method 22 check if every value is true
b.all()

True

In [80]:
a

array([2, 5, 6, 7, 8, 9])

In [81]:
b

array([10,  5,  7, 10,  7])

In [84]:
#Method 23 sort all values are stored in array
a.sort() 
a

array([2, 5, 6, 7, 8, 9])

In [85]:
#Method 24 return unique values repetation are stoped
np.unique(b)


array([ 5,  7, 10])

In [86]:
a

array([2, 5, 6, 7, 8, 9])

In [87]:
b

array([10,  5,  7, 10,  7])

In [88]:
#Method 25 this function save the file
np.save('loada',a)

In [90]:
#Method 26 this function load the file
new = np.load('loada.npy')
new

array([2, 5, 6, 7, 8, 9])

In [99]:
#Method 27 this function save the more than one file
np.savez('loadab',a,b)

In [102]:
#Method 28 this function load the more than one file
new = np.load('loadab.npz',a,b)
new

In [103]:
f = np.random.randn(3,2)
s = np.random.randn(2,3)

In [104]:
#Method 29 this function perform dot product
f.dot(s)

array([[-2.7859652 , -2.34405683, -1.68254651],
       [-1.79321568, -1.30489317, -0.67513372],
       [-1.34353216, -1.90720547, -2.36531036]])

In [105]:
#Method 30
s.transpose()

array([[-1.64713754, -1.3629105 ],
       [-1.51618425, -0.30238432],
       [-1.25545251,  0.86593618]])

In [106]:
#Method31
s.trace()


-1.949521861767017

In [107]:
a

array([2, 5, 6, 7, 8, 9])

In [108]:
#Method 32 this function return the minimum value
a.min()

2

In [109]:
#Method 33 this function return the maximmum value
a.max()

9

In [112]:
#Method 34 Minimum index value among the indexes of elements of an array
a.argmin()

0

In [113]:
#Method 35 Minimum index value among the indexes of elements of an array
a.argmax()

5

In [115]:
#Method 36: randint. This funciton is used to generate random
arr = np.random.randint(1,10,2)
arr

array([9, 8])

In [116]:
#Method 37: Round.
np.round(16.055, 2), round(16.055, 2)

(16.06, 16.05)

In [117]:
#Method 38:  sine of one angle:
np.sin(np.pi/2.)

1.0

In [118]:
#Method 39: LCM
np.lcm(12, 20)

60

In [119]:
#Method 40 GCD
np.gcd(20,4)

4

In [120]:
#Method 41: cos.
np.cos(np.array([0, np.pi/2, np.pi]))

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [123]:

#Method 42 prod
np.prod([12,5])

60

In [124]:
#Method 43. lower. Return an array with the elements converted to lowercase.
c = np.array(['A1B C', '1BCA', 'BCA1']) 
c

array(['A1B C', '1BCA', 'BCA1'], dtype='<U5')

In [125]:
#Method 44. Split. Split an array into 
x = np.arange(9.0)
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [126]:
#method 45 bolean
np.any([True, True, True, False])

True

In [127]:
np.random.seed(7)

In [128]:
#method 46
np.random.normal(size = (3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [129]:
#method 47
np.random.uniform(size =(3,3))

array([[0.38094113, 0.06593635, 0.2881456 ],
       [0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892]])

In [132]:
#method 48
np.random.gamma(4)

4.940921556547067

In [136]:
#method 49
x = np.ones((100, 100))
np.any(x != 1)


False

In [137]:
#method 50
ac = np.array([1.1,2.5,3.4,4.5])
np.ceil(ac)

array([2., 3., 4., 5.])